### PR TITLE
disable more irqs to fix am32 flash errors

### LINKED ISSUE #50: 电调透传（serial-esc-4way）刷写固件容易卡死
### Describe the bug

atbf  4.3.2rc3 在刷写 am32 电调固件的时候，大概率刷写失败，超时失去响应

### To Reproduce

1、NEUTRONRCF435SE /MINI  正常链接 am32 电调
2、am32电调上电
3、通过esc-configuator 刷写am32 电调
4、刷写会卡死、失去响应

### Expected behavior

期望能够正常刷写am32 电调固件

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```
```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `resource show all`
```
与配置信息无关

### Flight controller

NEUTRONRCF435SE / NEUTRONF435MINI / EMSRPROTO2

### Other components

_No response_

### How are the different components wired up

_No response_

### Add any other context about the problem that you think might be relevant here

_No response_

### PR DESCRIPTION
**Pull request by shanggl**
因为在刷写电调的过程中刷写电调的bug，根据at32的特性，关闭部分中断，保证 esc-4-way 模拟串口不受影响 
#50

### CODE REVIEW

File: src/main/io/serial_4way_avrootloader.c [hunk 1]
```diff
@@ -190,10 +201,19 @@ static uint8_t BL_ReadBuf(uint8_t *pstring, uint8_t len)
...
+    {
         //re-enable exint
         EXINT->inten=ExIntReg;
-	}
+        NVIC_EnableIRQ(EXINT9_5_IRQn);
+        NVIC_EnableIRQ(EXINT15_10_IRQn);
+        NVIC_EnableIRQ(TMR20_OVF_IRQn);
+        //disable USB
+        NVIC_EnableIRQ(OTGFS1_IRQn);
+        //disable uart 1\2
```
Comment (DusKing1) [inline src/main/io/serial_4way_avrootloader.c]: Mis-typing.

File: src/main/io/serial_4way_avrootloader.c [hunk 2]
```diff
@@ -190,10 +201,19 @@ static uint8_t BL_ReadBuf(uint8_t *pstring, uint8_t len)
...
 #if defined(AT32F43x)
-    ATOMIC_BLOCK(NVIC_PRIO_MAX){
+    {
         //re-enable exint
         EXINT->inten=ExIntReg;
-	}
+        NVIC_EnableIRQ(EXINT9_5_IRQn);
+        NVIC_EnableIRQ(EXINT15_10_IRQn);
+        NVIC_EnableIRQ(TMR20_OVF_IRQn);
+        //disable USB
```
Comment (DusKing1) [inline src/main/io/serial_4way_avrootloader.c]: Mis-typing.

File: src/main/io/serial_4way_avrootloader.c [hunk 3]
```diff
@@ -164,10 +164,21 @@ static uint8_t BL_ReadBuf(uint8_t *pstring, uint8_t len)
...
         ExIntReg=EXINT->inten;
         EXINT->inten=0;//DISABLE ALL EXINT
+        //disable 5-15 EXINT
+        NVIC_DisableIRQ(EXINT9_5_IRQn);
+        NVIC_DisableIRQ(EXINT15_10_IRQn);
+        //disable USB TIMER
+        NVIC_DisableIRQ(TMR20_OVF_IRQn);
+        //disable USB
+        NVIC_DisableIRQ(OTGFS1_IRQn);
+        //disable uart 1\2
```
Comment (DusKing1) [inline src/main/io/serial_4way_avrootloader.c]: 1/2/3

**Review by DusKing1 — CHANGES_REQUESTED** [review]

**Review by DusKing1 — APPROVED** [review]
